import {
  streamText,
  type UIMessage,
  convertToModelMessages,
  stepCountIs,
} from "ai";
import { anthropic } from "@ai-sdk/anthropic";
import { createTools } from "@/lib/ai/tools";
import { SYSTEM_PROMPT } from "@/lib/ai/prompts";
import { createClient } from "@/lib/supabase/server";
import { prisma } from "@/lib/db";
import type { Prisma } from "@/generated/prisma/client";

export async function POST(req: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const {
    messages,
    conversationId,
  }: { messages: UIMessage[]; conversationId?: string } = await req.json();

  // Verify conversation ownership if provided
  if (conversationId) {
    const existing = await prisma.conversation.findFirst({
      where: { id: conversationId, userId: user.id },
      select: { id: true },
    });
    if (!existing) {
      return Response.json({ error: "Conversation not found" }, { status: 404 });
    }
  }

  const result = streamText({
    model: anthropic("claude-sonnet-4-5-20250929"),
    providerOptions: {
      anthropic: {
        thinking: { type: "enabled", budgetTokens: 10000 },
      },
    },
    system: SYSTEM_PROMPT,
    messages: await convertToModelMessages(messages),
    tools: createTools(user.id),
    stopWhen: stepCountIs(5),
    onStepFinish: async ({ toolResults }) => {
      // Persist briefs generated by the AI
      if (!toolResults) return;
      for (const toolResult of toolResults) {
        if (toolResult.toolName === "generateBrief") {
          const output = toolResult.output as {
            data?: { title: string; content: Prisma.InputJsonValue };
          };
          if (!output?.data) continue;
          const { title, content } = output.data;
          await prisma.brief.create({
            data: {
              userId: user.id,
              conversationId: conversationId || null,
              title,
              content,
              status: "DRAFT",
            },
          });
        }
      }
    },
  });

  return result.toUIMessageStreamResponse();
}
